[package]
name = "nui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.15"
flume = "0.10.12"
rand = "0.8.5"
assert_float_eq = "1.1.3"